# Site settings
title: CI-Connect
email: enquiries@ci-connect.co.uk
description: > # this means to ignore newlines until "baseurl:"
  CI-Connect specialises in the design, installation and support of easy to use and reliable collaboration solutions for business, education, healthcare and government. CI-Connect will help your organisation enhance communication, improve productivity and increase efficiency with a number of offerings available.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ciconnect.github.io" # the base hostname & protocol for your site
timezone: Europe/London


# Build settings
markdown: kramdown
highlighter: pygments
sass:
    sass_dir: _sass