# Site settings
title: CI-Connect
slogan: Do more. Travel less. Be present.
email: enquiries@ci-connect.co.uk
telephone: "02034342030"
address: > 
  CI-Connect Ltd c/o Dragon Enterprise Centre, 
  28 Stephenson Road, LEIGH-ON-SEA, Essex, SS9 5LY
description: >
  CI-Connect specialises in the design, installation and support of easy 
  to use and reliable collaboration solutions for business, education, 
  healthcare and government. CI-Connect will help your organisation enhance 
  communication, improve productivity and increase efficiency with a number 
  of offerings available.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ciconnect.github.io" # the base hostname & protocol for your site
timezone: Europe/London

copyright: CI-Connect Ltd. Some rights reserved
# Build settings
markdown: kramdown
highlighter: pygments
sass:
    sass_dir: _sass